Insert into secteur(id_secteur, nom_secteur,	slug_secteur, code_type_activite) VALUES
(9,	"Géomètre expert",	"geometre-expert",	4),
(10,	"Ingénierie VRD",	"ingenierie-vrd",	4),
(11,	"Immobilier",	"immobilier",	4),
(12,	"Expertise foncière",	"expertise-fonciere",	4),
(37,	"Tabac",	"tabac",	1),
(40,	"Produits bio et écoproduits",	"produits-bio-et-ecoproduits",	2),
(41,	"Presse / librairie",	"presse-librairie",	2),
(42,	"Plats à emporter / restaurant",	"Plats-a-emporter-restaurant",	2),
(43,	"Matériel médicale",	"materiel-medicale",	2),
(71,	"Vins et spiritueux",	"vins-caviste",	2),
(73,	"Superette",	"superette",	2),
(76,	"Presse / librairie",	"presse-librairie",	2),
(79,	"Fromager",	"fromager-creme-lait",	2),
(80,	"Fleuristes",	"fleuristes",	2),
(81,	"Épicerie fine",	"epicerie-fine",	2),
(82,	"Boulangerie / pâtisserie / chocolaterie",	"boulangerie-patisserie-chocolaterie",	2),
(83,	"Boucherie / charcuterie / traiteur",	"boucherie-charcuterie-traiteur",	2),
(84,	"Œufs",	"oeufs-fermier-poules",	1),
(85,	"Vin",	"vin-anjou",	1),
(86,	"Viande",	"viande-colis-volaille",	1),
(87,	"Miel/confiture",	"miel-confiture-bonbons",	1),
(88,	"Lait / produits laitiers",	"lait-fromage-chevre-vache",	1),
(89,	"Fruits / légumes",	"fruits-legumes-panier",	1),
(90,	"Fleurs / plantes / plan",	"fleurs-plantes-plans-graines",	1),
(91,	"Champignons",	"Champignons-champignonnieres",	1),
(96,	"Farine",	"farine",	1),
(97,	"Fruits secs / infusion",	"fruits-secs",	1),
(99,	"Fruits et légumes",	"fruits-et-legumes",	2),
(101,	"Bière",	"bierre-liqueur-alcool",	1),
(102,	"Savon / cosmétique",	"savon-cosmetique-artisanal",	1),
(106,	"Couture",	"couture",	1),
(107,	"Mécanique / garage / réparation",	"garage-reparation-auto",	4),
(108,	"Pour les animaux",	"pour-les-animaux",	4),
(109,	"Santé / bien-être",	"soin-a-la-personne",	3),
(110,	"Informatique",	"informatique",	4),
(111,	"Friperie / textile",	"friperie-vetements",	2),
(114,	"Déco / intérieur",	"deco-interieur",	4),
(115,	"Image / communication",	"image-communication",	4),
(116,	"Bars / Restaurants / Hotels",	"bar-restaurant-hotel",	2),
(117,	"Restauration à emporter",	"restauration-rapide",	4),
(118,	"Loisirs / jeux",	"loisirs-jeux",	2),
(119,	"Bâtiment",	"artisan-habitat",	4),
(138,	"Mercerie / couture",	"Mercerie-couture",	2),
(149,	"Terrine",	"terrine",	1),
(157,	"Pâtes fraîches",	"pates-fraiches",	1),
(159,	"Pains",	"pains",	1),
(164,	"Escargots",	"escargots",	1),
(167,	"Poissons",	"poissons",	1),
(174,	"Torréfacteur",	"torrefacteur",	2),
(175,	"Pour les animaux",	"pour-les-animaux",	2),
(195,	"Assurances (Gestion des risques)",	"assurances",	4),
(196,	"Transport et Logistique",	"transports-logistiques",	4),
(199,	"Immobilier",	"immobilier",	3),
(200,	"Services à domicile",	"services-a-domicile",	3),
(201,	"Coiffeurs",	"coiffeurs",	3),
(202,	"Agriculteur",	"agriculteur",	1),
(203,	"Sécurité des biens et des personnes",	"securite-des-biens-et-des-personnes",	4),
(205,	"Sécurité",	"securite",	3),
(206,	"Artisanat",	"artisanat",	1),
(211,	"Conseil",	"conseil",	4),
(213,	"Aliments et compléments alimentaires",	"aliments-et-complements-alimentaires",	1);


